### ISSUE TITLE
Why not support Python 3.7

### ISSUE THREAD

**Issue by sunhailin-Leo** [iwpnd/pyle38#13]
* How can i use this lib on python3.7

**Comment by iwpnd** [comment]
Pyle38 uses a very alpha version of aioredis underneath which caused an issue with connections sometimes not closing properly in garbage collection. Turned out it was a bug in asnycio that only later has been fixed in 3.8. 

I will try 3.7 again in a later Release of aioredis, but until then it's fixed to 3.8.

**Comment by sunhailin-Leo** [comment]
> Pyle38 uses a very alpha version of aioredis underneath which caused an issue with connections sometimes not closing properly in garbage collection. Turned out it was a bug in asnycio that only later has been fixed in 3.8.
> 
> I will try 3.7 again in a later Release of aioredis, but until then it's fixed to 3.8.

* Maybe you can use [aredis](https://github.com/NoneGG/aredis) instead of aioredis.

**Comment by iwpnd** [comment]
Pretty happy with the new aioredis api, actually. But I will check it out, thank you. 
What keeps people from using python 3.8?

**Comment by sunhailin-Leo** [comment]
> Pretty happy with the new aioredis api, actually. But I will check it out, thank you.
> What keeps people from using python 3.8?

Personally, the main reason we don't use Python 3.8 is because the online environment takes a long time to maintain, but I'm considering moving to Python 3.8 as well.
